#!/usr/bin/env node
// Generates src/lib/contact/glyphs.ts: the outlines of every character a revealed contact detail can
// contain, extracted from the site's own font (Inter, the latin subset @fontsource ships). The reveal
// endpoint (src/pages/api/contact/reveal.ts) composes these into one path server-side, so the phone
// number reaches the browser as shapes drawn on a canvas, never as text. docs/contact-reveal.md.
//
// Run after changing a contact value to include a character outside CHARSET, or the font:
//   node scripts/contact-glyphs.mjs
// fontkitten and @fontsource-variable/inter are devDependencies used only here; the generated file is
// committed and nothing reads the font at request time.

import { readFileSync, writeFileSync } from 'node:fs';
import { create } from 'fontkitten';

const FONT = 'node_modules/@fontsource-variable/inter/files/inter-latin-wght-normal.woff2';
const OUT = 'src/lib/contact/glyphs.ts';
// Phone punctuation plus what an email would need, so adding an email detail needs no rerun.
const CHARSET = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@.-_+() ';

// The variable font's default instance is wght 400, the site's body weight. (fontkitten's
// getVariation() returns an instance without a cmap, so named weights are not an option here.)
const font = create(readFileSync(FONT));

const round = (n) => Math.round(n);
const OPS = { moveTo: 'M', lineTo: 'L', quadraticCurveTo: 'Q', bezierCurveTo: 'C', closePath: 'Z' };

const glyphs = {};
for (const ch of CHARSET) {
  const glyph = font.glyphForCodePoint(ch.codePointAt(0));
  const commands = glyph.path.commands.map(({ command, args }) => {
    const op = OPS[command];
    if (!op) throw new Error(`unexpected path command ${command} in "${ch}"`);
    return [op, ...args.map(round)];
  });
  glyphs[ch] = { advance: round(glyph.advanceWidth), commands };
}

const body = `// GENERATED by scripts/contact-glyphs.mjs from Inter (wght 400). Do not edit by hand.
// Outlines in font units (y up, baseline at 0) for the characters contact details may contain.

export type GlyphCommand = [op: 'M' | 'L' | 'Q' | 'C' | 'Z', ...coords: number[]];
export interface GlyphOutline { advance: number; commands: GlyphCommand[] }

export const UNITS_PER_EM = ${font.unitsPerEm};
export const ASCENT = ${round(font.ascent)};
export const DESCENT = ${round(font.descent)};

export const GLYPHS: Record<string, GlyphOutline> = ${JSON.stringify(glyphs)};
`;
writeFileSync(OUT, body);
console.log(`wrote ${OUT}: ${Object.keys(glyphs).length} glyphs, ${(body.length / 1024).toFixed(1)} KiB`);
